# Generated by Django 5.2.11 on 2026-02-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoriler',
            options={'verbose_name': 'Kategoriler', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='kategoriler',
            name='ustkategori',
            field=models.ForeignKey(blank=True, help_text='Eğer bu kategori başka bir kategoriye bağlıysa burayı doldurunuz', null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.kategoriler'),
        ),
    ]
