# Generated by Django 5.2.11 on 2026-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_alter_kategoriler_options_kategoriler_ustkategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kategoriler',
            name='seo_title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
