# Generated by Django 5.2.11 on 2026-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_kategoriler_seo_description_kategoriler_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='slug',
            field=models.SlugField(blank=True, max_length=155, null=True, unique=True),
        ),
    ]
