# Generated by Django 5.2.11 on 2026-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_etiketler_urunler_etiketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='urunresimleri'),
        ),
    ]
