# Generated by Django 5.2.11 on 2026-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_urunler_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='anasayfa',
            field=models.BooleanField(default=False),
        ),
    ]
