# Generated by Django 5.2.11 on 2026-02-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_urunler_anasayfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varyasyonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=155)),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stok', models.IntegerField(blank=True, null=True)),
                ('aktifmi', models.BooleanField(default=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='urunresimleri')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.urunler')),
            ],
            options={
                'verbose_name': 'Varyasyon',
                'verbose_name_plural': 'Varyasyonlar',
            },
        ),
    ]
