# Generated by Django 5.2.11 on 2026-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0010_varyasyonlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varyasyonlar',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='varyasyonresimleri'),
        ),
    ]
