# Generated by Django 5.2.11 on 2026-02-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0011_alter_varyasyonlar_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varyasyonlar',
            name='isim',
        ),
        migrations.AddField(
            model_name='varyasyonlar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.varyasyonlar'),
        ),
    ]
