# Generated by Django 5.2.11 on 2026-02-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0012_remove_varyasyonlar_isim_varyasyonlar_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='varyasyonlar',
            name='varyason',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
