# Generated by Django 5.2.11 on 2026-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0013_varyasyonlar_varyason'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
