# Generated by Django 5.2.11 on 2026-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0014_kategoriler_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='menuden_goster',
            field=models.BooleanField(default=True),
        ),
    ]
